name: Build Docker image

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Build Docker images
          id: docker_build
          uses: docker/build-push-action@v2.3.0
          with:
              push: false
              context: .
              file: Dockerfile
              tags: bbaovanc/dotfiles:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
