on: [push]
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                image: [archlinux-base, archlinux-base-devel]
        runs-on: ubuntu-latest

        steps:
        #- uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Generate Dockerfile
          run: make dockerfiles/${{ matrix.image }}

        - name: Build Docker images
          id: docker_build
          uses: docker/build-push-action@v2.3.0
          with:
              push: true
              file: dockerfiles/${{ matrix.image }}
              tags: bbaovanc/dotfiles:${{ matrix.image }}

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
